name: GitHub Actions - Pull Request Template Basico
run-name: Running - ${{ github.event_name }}
on:
  pull_request:
    branches: ## Branch pra onde vai
      # - develop
      - main
jobs:
  on-push:
    runs-on: ubuntu-latest
    steps:
      - name: Comentário
        run: |
          echo "Comentário PULL REQUEST WORKFLOW - Basic"
