name: Github actions - Push Template Basic
run-name: Running - ${{ github.event_name }}
on:
  push:
    paths:
      - "**.txt"

jobs:
  on-push:
    runs-on: ubuntu-latest
    steps:
      - name: Comment
        run: echo "PUSH Workflow comment - Path"
